stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - artifact

cache:          
 paths:
   - .m2/repository
 key: "maven-cache"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./mvnw compile -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: eclipse-temurin:21-jdk-alpine
  script:
    - ./mvnw test -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

performance-test-job:   # This job also runs in the test stage.
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  image: eclipse-temurin:21-jdk-alpine
  script:
    - echo "This will take about 5 minutes."
    - ./mvnw test -Dtest=TestPerformance

artifact-job:      # This job runs in the artifact stage.
  stage: artifact  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  artifacts:
        paths:
            - target/tour-guide.jar
        expire_in: 5 day
